name: niv-managed dependency updates
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run this every day at 4:00am
    - cron: "0 4 * * *"
  workflow_dispatch:
jobs:
  niv-updater:
    strategy:
      matrix:
        dep:
          - nixpkgs
          - pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      # notice there is no checkout step
      - name: niv-updater-action
        uses: knl/niv-updater-action@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch_prefix: "update/${{ matrix.dep }}"
          whitelist: ${{ matrix.dep }}
          title_prefix: "chore(deps/${{ matrix.dep }}):"
